### PR TITLE
Combo of all commits/PRs (rebased with all conflicts resolved) to save ya reviewing them all, if you prefer all-at-once

### PR DESCRIPTION
**Pull request by rdkls**
hope I'm actually being helpful here :)

### CODE REVIEW

**Comment by ArjenSchwarz** [comment]
Sorry @rdkls I prefer the PRs separate as you originally made them so I'll look at those later in the week when I've got the time. That said, the first thing needed to fix in those other PRs is that you've got the bastions as separate ECR repos (bastion-*) instead of tags within the single repo. If you can change that already, that would be great.

Also, thanks for your contributions!

**Comment by rdkls** [comment]
No probs :) Sorry about the conflicts ... a couple of different features change same parts of the code ( why I thought it might be kinder to just do the integration for you)

**Comment by ArjenSchwarz** [comment]
Actually, I was wrong about my comment for what needs to be fixed. Because it was for the task definitions, which obviously have the names like that. I just realised that I don't seem to have code written for creating the task definitions. A bit of an oversight there...

**Comment by rdkls** [comment]
I've written code today in create-bastion/index.py
If task definition for the user doesn't exist (or uses old Task Role) create a new one
Currently having issues allowing ECS to assume the role, but when I sort that will push to the feat/ensure_ecs_task_definition branch

**Comment by rdkls** [comment]
though maybe this is something better done when building the image ....

**Comment by ArjenSchwarz** [comment]
It should either be done when building the image, or with a separate template. After all, when you update the image, you don't need to update the task definition anymore.

Also, I realise none of this is made easy by my complete lack of high-level documentation here. I am working on that, but had to focus on preparing for the workshop I'm doing about it tomorrow first.

**Pull request closed without merging**
